package interviewquestions.java;

/**
 * Players generally sit in a circle. The player designated to go first
 * says the number "1", and each player thenceforth counts one number in turn.
 * However, any number divisible by 'A' e.g. three is replaced by the word fizz
 * and any divisible by 'B' e.g. five by the word buzz.
 * Numbers divisible by both become fizz buzz. A player who hesitates or makes
 * a mistake is either eliminated.
 *
 * Write a program that prints out the the pattern generated by such a scenario
 * given the values of 'A'/'B' and 'N' which are read from an input text file.
 * The input text file contains three space delimited numbers i.e. A, B, N.
 * The program should then print out the final series of numbers using 'F'
 * for fizz, 'B' for 'buzz' and 'FB' for fizz buzz.
 */
public class FizzBuzz {
  public static String fizzbuzz(int count, int A, int B) {
    StringBuilder res = new StringBuilder();
    for (int i = 1; i <= count; i++) {
      String tmp = "";
      if ((i % A) == 0) tmp += "F";
      if ((i % B) == 0) tmp += "B";
      if (tmp.isEmpty()) tmp = String.valueOf(i);

      res.append(tmp);
      res.append(' ');
    }

    return res.toString().trim();
  }

  public static void main (String[] args) {
    test(fizzbuzz(10, 3, 5).equals("1 2 F 4 B F 7 8 F B"));
    test(fizzbuzz(15, 2, 7).equals("1 F 3 F 5 F B F 9 F 11 F 13 FB 15"));
    test(fizzbuzz(15, 2, 7).equals("1 F 3 F 5 F B F 9 F 11 F 13 FB 15"));
    test(fizzbuzz(26, 3, 5).equals("1 2 F 4 B F 7 8 F B 11 F 13 14 FB 16 17 F 19 B F 22 23 F B 26"));
    test(fizzbuzz(20, 2, 5).equals("1 F 3 F B F 7 F 9 FB 11 F 13 F B F 17 F 19 FB"));
    test(fizzbuzz(10, 1, 1).equals("FB FB FB FB FB FB FB FB FB FB"));
    test(fizzbuzz(10, 1, 2).equals("F FB F FB F FB F FB F FB"));
    test(fizzbuzz(1, 1, 1).equals("FB"));
    test(fizzbuzz(0, 1, 1).equals(""));
  }

  public static void test(boolean condition) {
    // assertions are disabled by default in java, mimic their behaviour here
    if (!condition) {
      throw new AssertionError("invalid test");
    }
  }
}
